### ISSUE TITLE
Create a user interface add new taxi

### ISSUE THREAD

**Issue by amjedonline** [amjedonline/carbitrator#4]
**An interface to add new taxi with following details:**
- Number
- Model
- Manufacturer
- Owner name
- Colour
- Motor expire date
- Insurance number
- Insurance expire date
- PCO License number (http://www.pcodriverswanted.com/pco-license/_
- PCO License expiry date
- Taxi capacity
- Speed KMH
- Maximum Luggage (KG)

**Comment by amjedonline** [comment]
Checked in feature, need to add automated test cases ...

**Comment by sonerd** [comment]
- Is number == KFZ Kennzeichen ?
- one additional field could be `city`

**Comment by amjedonline** [comment]
yes supposed to be KFZ. There could also be additional fields like owner, address etc.. please compose a list in the Evernote document _alotaksim-admin-panel-requirements_
